"""Create conversations and messages tables

Revision ID: 6cfc3bbfe33b
Revises: cc0cda6e9030
Create Date: 2025-02-26 20:22:22.768527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cfc3bbfe33b'
down_revision: Union[str, None] = 'cc0cda6e9030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_title'), 'conversations', ['title'], unique=False)
    op.alter_column('messages', 'embedding',
               existing_type=postgresql.ARRAY(sa.REAL()),
               type_=postgresql.ARRAY(sa.FLOAT(precision=6)),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'embedding',
               existing_type=postgresql.ARRAY(sa.FLOAT(precision=6)),
               type_=postgresql.ARRAY(sa.REAL()),
               existing_nullable=True)
    op.drop_index(op.f('ix_conversations_title'), table_name='conversations')
    # ### end Alembic commands ###
